name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Nx CLI
        uses: actions/cache@v2
        with:
          path: ~/.npm-global # Adjust the path as needed
          key: nx-cli-${{ runner.os }}
          restore-keys: |
            nx-cli-

      - name: Install Nx CLI
        run: npm install -g @nrwl/cli

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase
        run: |
          firebase use --token FIREBASE_TOKEN

      - name: Deploy React App to Firebase
        run: npm run build:react
