name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Nx CLI
        run: npm install -g @nrwl/cli

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Firebase
        run: |
          firebase use --token FIREBASE_TOKEN

      - name: Deploy React App to Firebase
        run: npm run deploy:react-host

        # 2