name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase Login
        run: |
          echo -e "\n" | firebase login --interactive
        # Automatically accepts the default (Y) when prompted
        env:
          FIREBASE_CLI_DEPLOY_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Set up Firebase
        run: |
          firebase use --token $FIREBASE_CLI_DEPLOY_TOKEN
        env:
          FIREBASE_CLI_DEPLOY_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy React App to Firebase
        run: npm run deploy:react-host

        # 1